# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/fifo64x16/fifo64x16.xci
# IP: The module: 'fifo64x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/fifo64x16/fifo64x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo64x16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/fifo64x16/fifo64x16/fifo64x16.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo64x16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/fifo64x16/fifo64x16.xci
# IP: The module: 'fifo64x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/fifo64x16/fifo64x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo64x16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/fifo64x16/fifo64x16/fifo64x16.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo64x16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
