# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/fp_adder_subtracter/fp_adder_subtracter.xci
# IP: The module: 'fp_adder_subtracter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/fp_adder_subtracter/fp_adder_subtracter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_adder_subtracter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/fp_adder_subtracter/fp_adder_subtracter.xci
# IP: The module: 'fp_adder_subtracter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/fp_adder_subtracter/fp_adder_subtracter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_adder_subtracter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
