# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/axis_broadcaster_0/axis_broadcaster_0.xci
# IP: The module: 'axis_broadcaster_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/axis_broadcaster_0/axis_broadcaster_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_broadcaster_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/axis_broadcaster_0/axis_broadcaster_0.xci
# IP: The module: 'axis_broadcaster_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/IVA/Research/multi_stream_cusum_anomaly_detector/multi_stream_cusum_anomaly_detector.srcs/sources_1/ip/axis_broadcaster_0/axis_broadcaster_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_broadcaster_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
